### ISSUE TITLE
Error on Startup (first install)

### ISSUE THREAD

**Issue by danielgangl** [lmstudio-ai/.github#25]
Downloaded LM Studio for Mac (M1). Moved to application folder. Opened it and got this error:

<img width="524" alt="image" src="https://github.com/lmstudio-ai/.github/assets/46197733/ab7a6f71-a627-4e69-a6b9-166074f3ef16">

Trying reinstalling a few times but same error.

Any solutions or workarounds?

**Comment by yagil** [comment]
Hi @danielgangl what happens when you run this in the Terminal?

Command to try 1:
```
ls ~/.cache
```

Command to try 2:

```
mkdir ~/.cache/lm-studio
```


**Possible cause:**
The `~/.cache` folder was created sometime in the past using elevated permissions

If the commands above return something like `permission denied` (assuming you DO NOT run them with `sudo`) then the way to work around it is:

```
sudo chown -R $(whoami):staff ~/.cache
chmod -R 755 ~/.cache
```

As always make sure you understand the implications and only run it if you want to!

**Comment by danielgangl** [comment]
Ah right - yeah that was the issue. Works now, thanks!
